module.exports = {
	JENA_HOST: process.env.JENA_HOST,
	JENA_PORT: 3030,
	PROLOG_HOST: process.env.PROLOG_HOST,
	PROLOG_PORT: 1234,
	INSERT: "INSERT",
	DELETE: "DELETE",
	FUSEKI_PASSWORD: process.env.FUSEKI_PASSWORD
};
